codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

component_management:
  individual_components:
    - component_id: core
      name: Core Logic
      paths:
        - "src/core/**"
    - component_id: ui
      name: UI Layer
      paths:
        - "src/ui/**"
